import React, { useEffect, useState } from "react";
import Head from "next/head";
import Navbar from "./Navbar";
import style from "../styles/Layout.module.scss";
import Carrito from "./Carrito";

function Layout({ children, title }) {
  const [showCarrito, setShowCarrito] = useState(false);

  const mostrarCarrito = () => {
    setShowCarrito(!showCarrito);
  };

  return (
    <div style={{ display: "grid" }}>
      <Head>
        <title>Tienda App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Quicksand:wght@300;400;500;600;700&display=swap"
          rel="stylesheet"
        />
      </Head>
      <Navbar showCarrito={mostrarCarrito} />

      <div className={style.body}>{children}</div>
      {showCarrito && <Carrito showCarrito={mostrarCarrito} />}
      <footer className={style.footer}>
        <p>
          Hecho por <span>Sebas Sotelo</span>
        </p>
      </footer>
    </div>
  );
}

export default Layout;
